/*:
 # The Swift Programming Language
 ## Contents
 ### [The Basics](The%20Basics)
 ### [Basic Operators](Basic%20Operators)
 ### [Strings and Characters](Strings%20and%20Characters)
 ### [Collection Types](Collection%20Types)
 ### [Control Flow](Control%20Flow)
 ### [Functions](Functions)
 ### [Closures](Closures)
 ### [Enumerations](Enumerations)
 ### [Structures and Classes](Structures%20and%20Classes)
 ### [Properties](Properties)
 ### [Methods](Methods)
 ### [Subscripts](Subscripts)
 ### [Inheritance](Inheritance)
 ### [Initialization](Initialization)
 ### [Deinitialization](Deinitialization)
 ### [Optional Chaining](Optional%20Chaining)
 ### [Error Handling](Error%20Handling)
 ### [Type Casting](Type%20Casting)
 ### [Nested Types](Nested%20Types)
 ### [Extensions](Extensions)
 ### [Protocols](Protocols)
 ### [Generics](Generics)
 ### [Automatic Reference Counting](Automatic%20Reference%20Counting)
 ### [Memory Safety](Memory%20Safety)
 ### [Access Control](Access%20Control)
 ### [Advanced Operators](Advanced%20Operators)
 */
